### ISSUE TITLE
老哥，我拉取了仓库，怎么在luci-app里找不到啊

### ISSUE THREAD

**Issue by JohnLennon666** [lucikap/luci-app-ua2f#3]
用的L大的源码，拉取的
git clone https://github.com/lucikap/luci-app-ua2f.git package/luci-app-ua2f
也没有报错
![image](https://github.com/user-attachments/assets/0181500c-d28e-4e68-97f8-48afc1873aa4)
![image](https://github.com/user-attachments/assets/f5f5cf2b-99fb-49f4-a701-2f254f332af2)

**Comment by lucikap** [comment]
需要先选定ua2f主程序后才能在luci菜单显示

**Comment by lucikap** [comment]
需要先选定ua2f主程序后才能在luci菜单显示

**Comment by JohnLennon666** [comment]
![image](https://github.com/user-attachments/assets/43bc0d49-f7d7-4ed8-9da9-de6e374573da)
这里也选定了，还是没有，只能在路由器单独安装一遍

**Comment by lucikap** [comment]
你可以试试吧luci-app-ua2f移动到上一级目录中看看，可能是文件夹重名了

**Comment by Fourish** [comment]
![截图 2024-11-13 17-46-27](https://github.com/user-attachments/assets/3afd1e77-5b62-4c19-983e-7993f2a8ed11)
dump.txt内容为`Makefile:47: *** recipe commences before first target.  Stop.`
可能是这个原因

**Comment by Fourish** [comment]
@JohnLennon666 把luci-app-ua2f/luci-app-ua2f/Makefile:15 的 `DEPENDS:+=ua2f` 改成 `DEPENDS:=+ua2f`

**Comment by lucikap** [comment]
okok，非常谢谢指出问题
